version: 0.2
phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - IMAGE_URI="${REPOSITORY_URI}:${TAG}"
  build:
    commands:
      - docker build --tag "$IMAGE_URI" .
  post_build:
    commands:
      - docker push "$IMAGE_URI"
      - printf '[{"name":"simple-app","imageUri":"%s","logConfiguration": {"logDriver": "awslogs", "options": {
          "awslogs-group": "/ecs/ECS-LOGS",
          "awslogs-region": "us-east-1",
          "awslogs-stream-prefix": "ECS-%s"
        }}}]' "$IMAGE_URI" "$IMAGE_URI" > images.json
artifacts:
  files: images.json
